models/Form.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Form extends ActiveRecord
{


	public function rules(){

		return [

			[['names','last','email'],'required','message'=>'No se puede dejar vacio'],

			['email', 'email','message'=>'No es un email valido'],


			[['names','last','email','webpage','city'],'string','message'=>'No es valido'],

			[['phone','cellphone'],'integer','message'=>'Debe ingresar un numero'],

			 ['webpage', 'url', 'message' => 'No es valido'],



		];


	}
    
}

models/Imag.php
<?php

namespace app\models;

use yii\base\Model;
use yii\web\UploadedFile;

class Imag extends Model
{
   
    public $imagefile;

    public function rules()
    {
        return [
            [['imagefile'], 'file', 'skipOnEmpty' => false,'uploadRequired'=>'No se puede dejar vacio'],
             [['imagefile'], 'file', 'extensions' => 'png,jpg,jpeg','wrongExtension'=>'Solo se pueden subir imagenes con extension .png .jpg .jpeg'],
        ];
    }
    
    
}

models/Search.php
<?php

namespace app\models;

use yii\base\Model;


class Search extends Model
{
   
    public $items1 ;

    public $items2 ;

    
    
    
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use app\models\Form;

use app\models\Imag;

use app\models\Item;

use app\models\Search;

use yii\web\UploadedFile;

use yii\data\Pagination;

use yii\imagine\Image;

use app\models\Subclass;

use   yii\helpers\Json;




class SiteController extends Controller
{
   
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionItem(){

             $out = [];
        
            $id = $_POST['depdrop_parents'][0];

            switch ($id) {
              case 'atr1':
                  $out =  [
               ['id'=>'atr1', 'name'=>'<sub-cat-name1>'],
                ['id'=>'atr2', 'name'=>'<sub-cat-name2>'],
                ['id'=>'atr3', 'name'=>'<sub-cat-name3>']
             ];
                break;

              case 'atr2':
                $out =  [
                 ['id'=>'atr4', 'name'=>'<sub-cat-name4>'],
                  ['id'=>'atr5', 'name'=>'<sub-cat-name5>'],
                  ['id'=>'atr6', 'name'=>'<sub-cat-name6>']
               ];
                
                break;

              case 'atr3':

                $out =  [
               ['id'=>'atr7', 'name'=>'<sub-cat-name7>'],
                ['id'=>'atr8', 'name'=>'<sub-cat-name8>'],
                ['id'=>'atr9', 'name'=>'<sub-cat-name9>']
             ];
                
                break;
              
             
            }
            
                
                
                 echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            
        
       

    }

   
    public function actionIndex()
    {

       

        return $this->render('index');
    }



    public function actionShow(){


      $search=$_GET['Search']['items2'];

      

         

         

        $query= Form::find()->where(['category' =>$search]);


        $count=$query->count();


         $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $count,
        ]);



         $list=$query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();


         

              return $this->render('show',['list'=>$list,'pagination'=>$pagination]);

            

            

    }


    public function actionSearch(){

      


       $search= new Search();

        return $this->render('search',['search'=>$search]);

    }

   
  

    public function actionRegister(){

        $model = new Form();

        $image = new Imag();

          $search= new Search();


           $image->imagefile =UploadedFile::getInstance($image, 'imagefile');


        if(Yii::$app->request->post() ){

            $model->names=$_POST['Form']['names'];
            $model->last=$_POST['Form']['last'];
             $model->email=$_POST['Form']['email'];
              $model->adress=$_POST['Form']['adress'];
            $model->phone=$_POST['Form']['phone'];
             $model->cellphone=$_POST['Form']['cellphone'];
              $model->webpage=$_POST['Form']['webpage'];
            $model->city=$_POST['Form']['city'];
             $model->description=$_POST['Form']['description'];


           


           

            

               $model->extension=$image->imagefile->extension;

               $model->save();

             $image->validate();

             $image->imagefile->saveAs('images/' . $model->id. '.' . $image->imagefile->extension);

             Image::thumbnail('images/'.$model->id.'.'.$image->imagefile->extension, 240, 240)
    ->save('images/'.$model->id.'.'.$image->imagefile->extension, ['quality' => 80]);


          $model->category=$_POST['Search']['items2'];


           

           
          $model->save();

            return $this->render('index');

        }




        return $this->render('register',['model'=>$model,'image'=>$image,'search'=>$search]);

    }
   
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'App',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Menu Principal', 'url' => ['/site/index']],
            
           
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        
        <?= $content ?>
    </div>
</div>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/index.php
<?php


use yii\helpers\Html;
use yii\helpers\Url;


$this->title = 'App';
?>


    <span class="jumbotron down">
        

        <a><p ><?= Html::a('Registrarse' , ['site/register'],['class' => 'btn btn-lg btn-success']) ?></p></a>
    </span>


     <span class="jumbotron search ">
        

        <a >            <?= Html::a('Buscar  ' , ['site/search'],['class' => 'btn btn-lg btn-success']) ?></a>
    </span>

    

   


    <?php

   

   

?>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

use yii\helpers\Url;

use \kartik\depdrop\DepDrop;

$this->title = 'Registrarse';

$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

	<div class="footer">

    	<?= $form->field($model, 'names')->label('Nombres')->textInput(['maxlength'=>20]); ?>
    	<?= $form->field($model, 'last')->label('Apellidos')->textInput(['maxlength'=>20]); ?>
    	<?= $form->field($model, 'email')->label('Email')->textInput(['maxlength'=>30]); ?>
    	<?= $form->field($model, 'adress')->label('Direccion')->textInput(['maxlength'=>40]); ?>
    	<?= $form->field($model, 'phone')->label('Telefono')->textInput(['maxlength'=>20]); ?>
    	<?= $form->field($model, 'cellphone')->label('Celular')->textInput(['maxlength'=>20]); ?>
    	<?= $form->field($model, 'webpage')->label('Pagina web')->textInput(['maxlength'=>20]); ?>
    	<?= $form->field($model, 'city')->label('Ciudad')->textInput(['maxlength'=>20]); ?>

    	

    	<?= $form->field($model, 'description')->label('Descripcion')->textInput(['style'=>'height:200px','maxlength'=>240]); ?>
        <?=Html::label("Imagen");   ?>

       	<?= $form->field($image, 'imagefile')->fileInput([ 'class' => 'sr-only'])->label('Buscar una imagen ...',['class'=>'btn btn-default ']); ?>

         <?=  $form->field($search, 'items1')->dropdownList(['atr1'=>'Categoria 1','atr2'=>'Categoria 2','atr3'=>'Categoria 3'
              
             ],['prompt'=>'Seleccionar','id'=>'cat-id','class'=>'input-large form-control'])->label('Categoria 1');?>
          
         <?= $form->field($search, 'items2')->widget(DepDrop::classname(), [
    'options'=>['id'=>'subcat-id', 'class'=>'input-large form-control'],
    'pluginOptions'=>[
        'depends'=>['cat-id'],
        'placeholder'=>'Select...',
        'url'=>Url::to(['site/item'])
    ]
]);
    ?>
    
	</div>
    <div class="form-group">
        <div >
            <?= Html::submitButton('Crear', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>
<?php ActiveForm::end() ?>

views/site/search.php
<?php


use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Menu;
use yii\helpers\Url;
use app\models\Category;

use \kartik\depdrop\DepDrop;

$this->title = 'Busqueda';




$form = ActiveForm::begin([
        'action' => ['show'],
        'method' => 'get',
    ]) ?>

	<div class="footer">

    	 <?=  $form->field($search, 'items1')->dropdownList(['atr1'=>'Categoria 1','atr2'=>'Categoria 2','atr3'=>'Categoria 3'
              
             ],['prompt'=>'Seleccionar','id'=>'cat-id','class'=>'input-large form-control'])->label('Categoria 1');?>
          
         <?= $form->field($search, 'items2')->widget(DepDrop::classname(), [
    'options'=>['id'=>'subcat-id', 'class'=>'input-large form-control'],
    'pluginOptions'=>[
        'depends'=>['cat-id'],
        'placeholder'=>'Select...',
        'url'=>Url::to(['site/item'])
    ]
]);
    ?>
    	
    
	</div>
    <div class="form-group">
        <div >
            <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>
<?php ActiveForm::end() ?>

views/site/show.php
<?php




use yii\helpers\Html;
use yii\widgets\LinkPager;





$this->title = 'Resultados de busqueda';





?>








<?php foreach ($list as $form): ?>



	<span class="imgn">   <?= Html::img('images/'.$form->id.'.'.$form->extension);?> </span>

	<table class="footer">

     

   
    
     <li>  <?=Html::label("Nombre");   ?> </li>

       <p> <?= Html::encode("{$form->names} ") ?> </p>

       <li> <?=Html::label("Apellidos");   ?> </li>

       <p> <?= Html::encode("{$form->last} ") ?> </p>

        <li> <?=Html::label("Email");   ?> </li>

       <p> <?= Html::encode("{$form->email} ") ?> </p>

      <li> <?=Html::label("Direccion");   ?> </li>

       <p> <?= Html::encode("{$form->adress} ") ?> </p>


      <li>  <?=Html::label("Telefono");   ?> </li>

       <p> <?= Html::encode("{$form->phone} ") ?> </p>

       <li>  <?=Html::label("Celular");   ?>     </li>

       <p> <?= Html::encode("{$form->cellphone} ") ?> </p>

       <li> <?=Html::label("Telefono");   ?>      </li>

       <p> <?= Html::encode("{$form->webpage} ") ?> </p>

       <li>  <?=Html::label("Cuidad");   ?>    </li>

       <p> <?= Html::encode("{$form->city} ") ?> </p>

       <li>  <?=Html::label("Descripcion");   ?>    </li>

       <p> <?= Html::encode("{$form->description} ") ?> </p>


      



       
   </table>




<?php endforeach; ?>




<?= LinkPager::widget(['pagination' => $pagination]) ?>